# Nome da pipeline
name: Build, Test, e Deploy da aplicação para Azure Web App - InfraCodeDocs

# Disparar a pipeline em cada push para a branch main
on:
  push:
    branches:
      - main

# Jobs que serão executados
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # Configuração do Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Versão do Node.js

    # Instalar as dependências
    - name: Install dependencies
      run: npm install

    # Rodar os testes
    - name: Run tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    # Build da aplicação
    - name: Build Angular app
      run: npm run build-prod

    # Empacotar os arquivos de build em um arquivo .zip
    - name: Zip the build artifacts
      run: zip -r infra-code-docs-prod.zip dist/infra-code-docs-prod

    # Login no Azure usando Azure CLI
    - name: Azure Login
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    # Deploy no Azure Web App usando Azure CLI
    - name: Deploy to Azure Web App
      run: az webapp deploy --name 'InfraCodeDocs' --resource-group 'Estudo' --src-path ${{ github.workspace }}/infra-code-docs-prod.zip --type zip
